server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://120.78.168.146:3306/learn?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath*:/mapper/*Mapper.xml


  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
    spring:
      mvc: static-path-pattern=/static/**

